minVersion: 0.34.1
github:
  owner: getsentry
  repo: usage-accountant
changelogPolicy: auto
preReleaseCommand: bash ../sbin/bump-version-py.sh
releaseBranchPrefix: release-usage-accountant
targets:
  - name: pypi
  - name: sentry-pypi
    internalPypiRepo: getsentry/pypi
