minVersion: 0.34.1
github:
  owner: getsentry
  repo: usage-accountant
changelogPolicy: auto

statusProvider:
  name: github
artifactProvider:
  name: github

preReleaseCommand: bash ../scripts/bump-version-rust.sh
releaseBranchPrefix: release-usage-accountant-rust
targets:
  - name: crates
