name: build

on:
  push:
    branches:
      - main
      - release-usage-accountant-py/**
    paths:
      - py/**
  pull_request:
    paths:
      - py/**

jobs:
  dist:
    name: Create wheel and source distribution
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: "Prepare artifacts"
        working-directory: ./py
        run: |
          pip install wheel
          pip install build
          python -m build --wheel
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: py/dist/*
