name: CI for the python module
on:
  push:
    branches:
      - main
      - release-usage-accountant-py/**
    paths:
      - py/**
  pull_request:
    paths:
      - py/**

jobs:
  linting:
    name: "Run linters"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        working-directory: ./py
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
      - name: Run linter
        working-directory: ./py
        run: |
          black usageaccountant tests
          flake8 usageaccountant tests
  typing:
    name: "Type checking"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        working-directory: ./py
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements-test.txt
      - name: Run mypy
        run: |
          mypy . --strict
  tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        working-directory: ./py
        run: |
          pip install -r requirements-test.txt
      - name: Run tests
        run: py.test .
