name: CI for the Rust crate

on:
  push:
    branches:
      - main
      - release/**
    paths:
      - py/**
  pull_request:
    paths:
      - py/**

env:
  RUSTFLAGS: -Dwarnings

jobs:

  test:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: swatinem/rust-cache@v1
        with:
          key: ${{ github.job }}

      - name: Run Cargo Tests
        uses: actions-rs/cargo@v1
        working-directory: ./rust
        with:
          command: test
          args: --workspace
